

package ui.hotel;


import business.DB40Util.DB4OUtil;
import business.EcoSystem;
import business.hotel.Hotel;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import ui.HomePage;

/**
 *
 * @author  nemad
 */
public class HotelPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    
    /** Creates new form AdminWorkAreaJPanel */
    EcoSystem ecoSystem;
    Hotel hotel;
    JFrame mainJFrame;
    public HotelPanel(JFrame mainJFrame, Hotel hotel,EcoSystem ecoSystem) {
        initComponents();
        this.mainJFrame = mainJFrame;
        this.ecoSystem = ecoSystem;
        this.hotel = hotel;
        lblHotelName.setText(hotel.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        lblHotelName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userJButton.setText("Manage Hotel Info");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 200, 53));

        manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageEmployeeJButton.setText("Manage Rooms");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 200, 53));

        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageOrganizationJButton.setText("Manage Room Booking");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 200, 53));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Hotel :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, 40));

        lblHotelName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHotelName.setText("<value>");
        add(lblHotelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 130, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 70, 120, 53));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        HotelManageInfoPanel hotelManageInfoPanel = new HotelManageInfoPanel(mainJFrame, hotel, ecoSystem);
        mainJFrame.setContentPane(hotelManageInfoPanel);
        mainJFrame.revalidate();
        mainJFrame.repaint();
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        HotelMainMenu hotelMainMenu = new HotelMainMenu(mainJFrame, hotel, ecoSystem);
        mainJFrame.setContentPane(hotelMainMenu);
        mainJFrame.revalidate();
        mainJFrame.repaint();
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        BookRoom hotelOrderMenu = new BookRoom(mainJFrame, hotel, ecoSystem);
        mainJFrame.setContentPane(hotelOrderMenu);
        mainJFrame.revalidate();
        mainJFrame.repaint();
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        DB4OUtil dB4OUtil = DB4OUtil.getInstance();
        dB4OUtil.storeSystem(ecoSystem);
        HomePage newMainJFrame = new HomePage();
        newMainJFrame.setVisible(true);
        mainJFrame.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel lblHotelName;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
    
}
